[ip-reputation]

spoe-agent iprep-agent
    messages get-ip-reputation
    option var-prefix iprep
    timeout hello      2s
    timeout idle       30s
    timeout processing 10ms
    use-backend iprep-servers

spoe-message get-ip-reputation
    args ip=src
    event on-client-session
